"Font
set guifont=Courier\ New\ 12

"background
"set background=dark

"color scheme
colorscheme koehler 

"auto indent 缩进
set ai

"smart indent
set si

"vim history line number
set history=400

"always show current position
set ruler

"syntax hl
syntax enable

"highlight current line
set cursorline

"show line number
"set nu

"commander bar hight
set cmdheight=2

"set backspace
set backspace=eol,start,indent

"highlight search
set hlsearch

"enable file type plugin
filetype plugin on

"turn on backup
"set backup

